name: HeapDumper
main: org.powernukkit.plugins.heapdumper.HeapDumperPlugin
version: "1.0.0"
api: ["1.0.11"]
author: joserobjr
description: Adds a command to take a heap dump to analyze memory leak issues
website: https://github.com/PowerNukkit/HeapDumper-Plugin
commands:
  heapdump:
    description: Take a heap dump to analyze memory leak issues and save in the server's folder
    usage: "/heapdump <optional-file-name-without-extension>"
    permission: heapdumper.heapdump
  cleardump:
    description: Deletes a specific heap dump file
    usage: "/cleardump <file-name-with-or-without-extension>"
    permission: heapdumper.cleardump.single
  clearalldumps:
    description: Deletes all heap dump files at once
    usage: "/clearalldumps"
    permission: heapdumper.cleardump.all
permissions:
  heapdumper.heapdump:
    description: "Allows the user to run the heapdump command"
    default: false
  heapdumper.cleardump.single:
    description: "Allows the user to run the cleardump command"
    default: false
  heapdumper.cleardump.all:
    description: "Allows the user to run the clearalldumps command"
    default: false
  heapdumper.cleardump.*:
    description: "Allows the user to run the command that clears the dumps"
    default: false
    children:
      heapdumper.cleardump.single: true
      heapdumper.cleardump.all: true
  heapdumper.*:
    description: "Allows the user to run all the heapdumper commands"
    default: op
    children:
      heapdumper.heapdump: true
      heapdumper.cleardump.*: true
